services:
  mongo:
    image: mongo:6
    container_name: rameses-mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db

  rameses:
    build: .
    container_name: rameses-node
    restart: unless-stopped
    depends_on:
      - mongo
    command: ["node", "--env-file=.env", "app.js"]

volumes:
  mongo-data:
